initializr:
  javaVersions:
    - id: 17
      default: true
    - id: 11
      default: false
    - id: 1.8
      default: false
  languages:
    - name: Java
      id: java
      default: true
  packagings:
    - name: Jar
      id: jar
      default: true
    - name: War
      id: war
      default: false
  types:
    - name: Maven Project
      id: maven-project
      description: Generate a Maven based project archive
      tags:
        build: maven
        format: project
      default: true
      action: /starter.zip
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: false
      action: /starter.zip