spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    username: root
    password: secret-pw
  flyway:
    enabled: false
  sql:
    init:
      platform: mysql
      mode: always
